### PR TITLE
Uniqueness

### PR DESCRIPTION
**Pull request by udeved**
New:

* Gate of Laozi (4 limit)
*  Great tower (4 limit, upgradeable stone tower, 10 garrison bow tower)
* rammed earth walls, replaces Palisades, tier 1
* GovernmentCenter (1 limit)
* poison & fire arrows and tech for palace guard champs
* bring back rice 
* dock has 10 garrison, attack and small territory
*  new hero auras, updated techs
*  minister limit to 9

Fixes:

* tech
* portraits
* actors

Missing:

* those nice models from the forum thread for fortress, walls and big tower

Ideas:

* heros get abilities, similar to the upgrade mechanics for the champ archer demo

### CODE REVIEW

**Comment by 1237894** [comment]
The shrine is a building used for Shinto worship, only in Japan
What you did should be called Yuanmen. Yuanmen is a vocabulary derived from the ancient chariot cover tactics in the pre-Qin era. Later, due to its unique formation, it was used as an inspiration to design a gate and used as a symbolic building for the outer gates of military camps and government offices. It was the first to appear It was in the Shang Dynasty before Christianity
QQ截图20211013133924
src=http___s9 sinaimg cn_middle_59ca50c3xa67579a9ead8 690 refer=http___s9 sinaimg
src=http___static-bbs nubia cn_forum_201701_31_20170131210721fujz166n85v3 jpg refer=http___static-bbs nubia

**Comment by StanleySweet** [comment]
Should be possible yes, although I prefer rebases where possible. 

Due to the size of this PR, If you squash this and something slips the review, it will be impossible to diagnose see https://trac.wildfiregames.com/changeset/19095 for an example, I'm still cleaning up stuff that happened then in the main branch.

I really want to include the hans in A26 but I'm really scared this will delay even more their inclusion :/

**Comment by udeved** [comment]
`But having changes like the ones in the .gitignore file can't help but make me a little suspicious :P`

Wut? :D Used the template to kick out the match limitation to test heros and auras.

`That sounds dangerous and not cross platform?`

A windows or macos doesn't know soft links, symbolic links? I doubt that tbh.
Its just a grain and rice setup, field and granary are symbolic links to the template, so the AI can build whatever selected by the symlink. :p

**Comment by udeved** [comment]
Btw, my proposal would be, to cire some concerns, iron out imbalance, let the users have some test matched from the uniquness branch, I think the outcome could be "too powerful".

**Comment by StanleySweet** [comment]
> How so? the wall tower global template has this modification, ie readded, effects all civs.

Yeah but then the patch belongs to the main game not the hans. Anyway.

> I can assure you, no problem with symlink in git. The answer in that threads sums it up.
But lets separate for the moment your svn and the mod for a moment.
For now, the Han are not in your svn, I added the symlink solution until a decision is made if rice or not, atm its in, but easily to get rid of by changing that symlink.

Yeah point is this really easy to `forget`

> So I propose, until the Han go in your svn, we should leave the symlink in place, have users some testing etc, I am sure couple more PRs come in until it goes in your svn?

I hope users will test it yes, but I don't have much hope. And yeah probably more prs, hopefully not as big as this one.

**Comment by StanleySweet** [comment]
Also I really don't like comments in templates/actors

**Pull request merged**
